flags: {}
packages:
- containers
- containers-tests

### Uncoment the resolver you want to use and re-run `stack build/test/bench`.
# resolver: lts-10.0
resolver: lts-12.26

extra-deps:
- binary-0.8.8.0
